const PHOTOS = [
  "photos/2022 vacation-9696.webp",
  "photos/2022 vacation-9750.webp",
  "photos/2022 vacation-9815.webp",
  "photos/2022 vacation-9875.webp",
  "photos/2022 vacation-9882.webp",
  "photos/after.webp",
  "photos/animal.webp",
  "photos/April 5th-6495.webp",
  "photos/April 5th-6503.webp",
  "photos/Arugot Farms-0443.webp",
  "photos/bee .webp",
  "photos/Bessy.webp",
  "photos/bird after .webp",
  "photos/black and white.webp",
  "photos/boys trip NORTH-.webp",
  "photos/boys trip NORTH-7400272.webp",
  "photos/boys trip NORTH-7400340.webp",
  "photos/boys trip NORTH-7400382.webp",
  "photos/bucharest-varna-4124.webp",
  "photos/bucharest-varna-4178.webp",
  "photos/bucharest-varna-4267.webp",
  "photos/bucharest-varna-4308.webp",
  "photos/bucharest-varna-4374.webp",
  "photos/bucharest-varna-4503.webp",
  "photos/bucharest-varna-4657.webp",
  "photos/bucharest-varna-4828.webp",
  "photos/bucharest-varna-4863.webp",
  "photos/bucharest-varna-4886.webp",
  "photos/bucharest-varna-4900.webp",
  "photos/coffee-8145.webp",
  "photos/colorful.webp",
  "photos/deer.webp",
  "photos/far away.webp",
  "photos/Favorites-2.webp",
  "photos/flowers.webp",
  "photos/food.webp",
  "photos/framed.webp",
  "photos/greece all photos--17.webp",
  "photos/greece all photos-6699.webp",
  "photos/greece all photos-6889.webp",
  "photos/greece all photos-7072.webp",
  "photos/greece all photos-7091.webp",
  "photos/greece all photos-7094.webp",
  "photos/greece all photos-7118.webp",
  "photos/greece all photos-7125.webp",
  "photos/greece all photos-7407.webp",
  "photos/hot photo 2.webp",
  "photos/josiah after.webp",
  "photos/July 1-7393.webp",
  "photos/july 17th evening-3024.webp",
  "photos/july 17th evening-3046.webp",
  "photos/Leaf Regular.webp",
  "photos/lighthouse.webp",
  "photos/long exposure.webp",
  "photos/love.webp",
  "photos/may 17th -2127.webp",
  "photos/may 17th -2180.webp",
  "photos/may 17th -2772.webp",
  "photos/mo-9945.webp",
  "photos/morning jan 5th-9483.webp",
  "photos/morning jan 5th-9489.webp",
  "photos/morning shoot-7824.webp",
  "photos/morning.webp",
  "photos/music.webp",
  "photos/nature.webp",
  "photos/patriotic.webp",
  "photos/Photography Contest~Justin-0066.jpg 2.webp",
  "photos/Photography Contest~Justin-0094.webp",
  "photos/Photography Contest~Justin-0100.webp",
  "photos/Photography Contest~Justin-3748.webp",
  "photos/reedited again.webp",
  "photos/shadows.webp",
  "photos/snow january-9689.webp",
  "photos/Snow-8272.webp",
  "photos/starry guitar.webp",
  "photos/structure 2.webp",
  "photos/structure photo 1.webp",
  "photos/stuffs-5617.webp",
  "photos/sunset shoot-02479.webp",
  "photos/sunset shoot-02483.webp",
  "photos/sunset shoot-02485.webp",
  "photos/sunset shoot-02495.webp",
  "photos/sunset shoot-02532.webp",
  "photos/technology.webp",
  "photos/time.webp",
  "photos/truck new.webp",
  "photos/unbalanced.webp",
  "photos/vineyards morning-9591.webp",
  "photos/water.webp",
  "photos/your everyday.webp"
];
